window.esdocSearchIndex = [
  [
    "meeks-prf-js/src/ballot.js~ballot",
    "class/src/ballot.js~Ballot.html",
    "<span>Ballot</span> <span class=\"search-result-import-path\">meeks-prf-js/src/ballot.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/decimal9.js~decimal9",
    "class/src/decimal9.js~Decimal9.html",
    "<span>Decimal9</span> <span class=\"search-result-import-path\">meeks-prf-js/src/decimal9.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/decimal9.js~decimal9error",
    "class/src/decimal9.js~Decimal9Error.html",
    "<span>Decimal9Error</span> <span class=\"search-result-import-path\">meeks-prf-js/src/decimal9.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/decimal9.js~decimal9total",
    "class/src/decimal9.js~Decimal9Total.html",
    "<span>Decimal9Total</span> <span class=\"search-result-import-path\">meeks-prf-js/src/decimal9.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/constants.js~k",
    "variable/index.html#static-variable-K",
    "<span>K</span> <span class=\"search-result-import-path\">meeks-prf-js/src/constants.js</span>",
    "variable"
  ],
  [
    "meeks-prf-js/src/errors.js~meekimplementationerror",
    "class/src/errors.js~MeekImplementationError.html",
    "<span>MeekImplementationError</span> <span class=\"search-result-import-path\">meeks-prf-js/src/errors.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/errors.js~meekvalueerror",
    "class/src/errors.js~MeekValueError.html",
    "<span>MeekValueError</span> <span class=\"search-result-import-path\">meeks-prf-js/src/errors.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/progress.js~progress",
    "class/src/progress.js~Progress.html",
    "<span>Progress</span> <span class=\"search-result-import-path\">meeks-prf-js/src/progress.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/results.js~results",
    "class/src/results.js~Results.html",
    "<span>Results</span> <span class=\"search-result-import-path\">meeks-prf-js/src/results.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/status.js~status",
    "class/src/status.js~Status.html",
    "<span>Status</span> <span class=\"search-result-import-path\">meeks-prf-js/src/status.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/meek.js~tabulation",
    "class/src/meek.js~Tabulation.html",
    "<span>Tabulation</span> <span class=\"search-result-import-path\">meeks-prf-js/src/meek.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/util_basic.js~ubf",
    "variable/index.html#static-variable-UBF",
    "<span>UBF</span> <span class=\"search-result-import-path\">meeks-prf-js/src/util_basic.js</span>",
    "variable"
  ],
  [
    "meeks-prf-js/src/util_basic.js~utilbaseerror",
    "class/src/util_basic.js~UtilBaseError.html",
    "<span>UtilBaseError</span> <span class=\"search-result-import-path\">meeks-prf-js/src/util_basic.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/util_basic.js~utilbasicfunctions",
    "class/src/util_basic.js~UtilBasicFunctions.html",
    "<span>UtilBasicFunctions</span> <span class=\"search-result-import-path\">meeks-prf-js/src/util_basic.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/util_basic.js~utilvalueerror",
    "class/src/util_basic.js~UtilValueError.html",
    "<span>UtilValueError</span> <span class=\"search-result-import-path\">meeks-prf-js/src/util_basic.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/validate.js~validator",
    "class/src/validate.js~Validator.html",
    "<span>Validator</span> <span class=\"search-result-import-path\">meeks-prf-js/src/validate.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/with_json.js~withjson",
    "class/src/with_json.js~WithJson.html",
    "<span>WithJson</span> <span class=\"search-result-import-path\">meeks-prf-js/src/with_json.js</span>",
    "class"
  ],
  [
    "meeks-prf-js/src/meek.js~tabulate",
    "function/index.html#static-function-tabulate",
    "<span>tabulate</span> <span class=\"search-result-import-path\">meeks-prf-js/src/meek.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/ballot.js",
    "file/src/ballot.js.html",
    "src/ballot.js",
    "file"
  ],
  [
    "src/ballot.js~ballot#asarray",
    "class/src/ballot.js~Ballot.html#instance-method-asArray",
    "src/ballot.js~Ballot#asArray",
    "method"
  ],
  [
    "src/ballot.js~ballot#constructor",
    "class/src/ballot.js~Ballot.html#instance-constructor-constructor",
    "src/ballot.js~Ballot#constructor",
    "method"
  ],
  [
    "src/ballot.js~ballot#getmultiple",
    "class/src/ballot.js~Ballot.html#instance-method-getMultiple",
    "src/ballot.js~Ballot#getMultiple",
    "method"
  ],
  [
    "src/ballot.js~ballot#getrankings",
    "class/src/ballot.js~Ballot.html#instance-method-getRankings",
    "src/ballot.js~Ballot#getRankings",
    "method"
  ],
  [
    "src/ballot.js~ballot#isequal",
    "class/src/ballot.js~Ballot.html#instance-method-isEqual",
    "src/ballot.js~Ballot#isEqual",
    "method"
  ],
  [
    "src/ballot.js~ballot#isnotequal",
    "class/src/ballot.js~Ballot.html#instance-method-isNotEqual",
    "src/ballot.js~Ballot#isNotEqual",
    "method"
  ],
  [
    "src/ballot.js~ballot#tostring",
    "class/src/ballot.js~Ballot.html#instance-method-toString",
    "src/ballot.js~Ballot#toString",
    "method"
  ],
  [
    "src/ballot.js~ballot#valueof",
    "class/src/ballot.js~Ballot.html#instance-method-valueOf",
    "src/ballot.js~Ballot#valueOf",
    "method"
  ],
  [
    "src/big-integer.js",
    "file/src/big-integer.js.html",
    "src/big-integer.js",
    "file"
  ],
  [
    "src/constants.js",
    "file/src/constants.js.html",
    "src/constants.js",
    "file"
  ],
  [
    "src/decimal9.js",
    "file/src/decimal9.js.html",
    "src/decimal9.js",
    "file"
  ],
  [
    "src/decimal9.js~decimal9#constructor",
    "class/src/decimal9.js~Decimal9.html#instance-constructor-constructor",
    "src/decimal9.js~Decimal9#constructor",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#divideby",
    "class/src/decimal9.js~Decimal9.html#instance-method-divideBy",
    "src/decimal9.js~Decimal9#divideBy",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#isequal",
    "class/src/decimal9.js~Decimal9.html#instance-method-isEqual",
    "src/decimal9.js~Decimal9#isEqual",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#isgreater",
    "class/src/decimal9.js~Decimal9.html#instance-method-isGreater",
    "src/decimal9.js~Decimal9#isGreater",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#isgreaterequal",
    "class/src/decimal9.js~Decimal9.html#instance-method-isGreaterEqual",
    "src/decimal9.js~Decimal9#isGreaterEqual",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#isless",
    "class/src/decimal9.js~Decimal9.html#instance-method-isLess",
    "src/decimal9.js~Decimal9#isLess",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#islessequal",
    "class/src/decimal9.js~Decimal9.html#instance-method-isLessEqual",
    "src/decimal9.js~Decimal9#isLessEqual",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#isnotequal",
    "class/src/decimal9.js~Decimal9.html#instance-method-isNotEqual",
    "src/decimal9.js~Decimal9#isNotEqual",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#issafe",
    "class/src/decimal9.js~Decimal9.html#instance-method-isSafe",
    "src/decimal9.js~Decimal9#isSafe",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#minus",
    "class/src/decimal9.js~Decimal9.html#instance-method-minus",
    "src/decimal9.js~Decimal9#minus",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#negative",
    "class/src/decimal9.js~Decimal9.html#instance-method-negative",
    "src/decimal9.js~Decimal9#negative",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#plus",
    "class/src/decimal9.js~Decimal9.html#instance-method-plus",
    "src/decimal9.js~Decimal9#plus",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#times",
    "class/src/decimal9.js~Decimal9.html#instance-method-times",
    "src/decimal9.js~Decimal9#times",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#tonumber",
    "class/src/decimal9.js~Decimal9.html#instance-method-toNumber",
    "src/decimal9.js~Decimal9#toNumber",
    "method"
  ],
  [
    "src/decimal9.js~decimal9#tostring",
    "class/src/decimal9.js~Decimal9.html#instance-method-toString",
    "src/decimal9.js~Decimal9#toString",
    "method"
  ],
  [
    "src/decimal9.js~decimal9.max_safe_integer",
    "class/src/decimal9.js~Decimal9.html#static-get-MAX_SAFE_INTEGER",
    "src/decimal9.js~Decimal9.MAX_SAFE_INTEGER",
    "member"
  ],
  [
    "src/decimal9.js~decimal9.max_safe_value",
    "class/src/decimal9.js~Decimal9.html#static-get-MAX_SAFE_VALUE",
    "src/decimal9.js~Decimal9.MAX_SAFE_VALUE",
    "member"
  ],
  [
    "src/decimal9.js~decimal9.min_safe_integer",
    "class/src/decimal9.js~Decimal9.html#static-get-MIN_SAFE_INTEGER",
    "src/decimal9.js~Decimal9.MIN_SAFE_INTEGER",
    "member"
  ],
  [
    "src/decimal9.js~decimal9.min_safe_value",
    "class/src/decimal9.js~Decimal9.html#static-get-MIN_SAFE_VALUE",
    "src/decimal9.js~Decimal9.MIN_SAFE_VALUE",
    "member"
  ],
  [
    "src/decimal9.js~decimal9error#constructor",
    "class/src/decimal9.js~Decimal9Error.html#instance-constructor-constructor",
    "src/decimal9.js~Decimal9Error#constructor",
    "method"
  ],
  [
    "src/decimal9.js~decimal9total#constructor",
    "class/src/decimal9.js~Decimal9Total.html#instance-constructor-constructor",
    "src/decimal9.js~Decimal9Total#constructor",
    "method"
  ],
  [
    "src/decimal9.js~decimal9total#minus",
    "class/src/decimal9.js~Decimal9Total.html#instance-method-minus",
    "src/decimal9.js~Decimal9Total#minus",
    "method"
  ],
  [
    "src/decimal9.js~decimal9total#plus",
    "class/src/decimal9.js~Decimal9Total.html#instance-method-plus",
    "src/decimal9.js~Decimal9Total#plus",
    "method"
  ],
  [
    "src/errors.js",
    "file/src/errors.js.html",
    "src/errors.js",
    "file"
  ],
  [
    "src/errors.js~meekimplementationerror#constructor",
    "class/src/errors.js~MeekImplementationError.html#instance-constructor-constructor",
    "src/errors.js~MeekImplementationError#constructor",
    "method"
  ],
  [
    "src/errors.js~meekvalueerror#constructor",
    "class/src/errors.js~MeekValueError.html#instance-constructor-constructor",
    "src/errors.js~MeekValueError#constructor",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/meek.js",
    "file/src/meek.js.html",
    "src/meek.js",
    "file"
  ],
  [
    "src/meek.js~tabulation#constructor",
    "class/src/meek.js~Tabulation.html#instance-constructor-constructor",
    "src/meek.js~Tabulation#constructor",
    "method"
  ],
  [
    "src/meek.js~tabulation#tabulate",
    "class/src/meek.js~Tabulation.html#instance-method-tabulate",
    "src/meek.js~Tabulation#tabulate",
    "method"
  ],
  [
    "src/progress.js",
    "file/src/progress.js.html",
    "src/progress.js",
    "file"
  ],
  [
    "src/progress.js~progress#buildcomplete",
    "class/src/progress.js~Progress.html#instance-member-buildComplete",
    "src/progress.js~Progress#buildComplete",
    "member"
  ],
  [
    "src/progress.js~progress#callback",
    "class/src/progress.js~Progress.html#instance-member-callback",
    "src/progress.js~Progress#callback",
    "member"
  ],
  [
    "src/progress.js~progress#checktoupdate",
    "class/src/progress.js~Progress.html#instance-method-checkToUpdate",
    "src/progress.js~Progress#checkToUpdate",
    "method"
  ],
  [
    "src/progress.js~progress#completedlabel",
    "class/src/progress.js~Progress.html#instance-member-completedLabel",
    "src/progress.js~Progress#completedLabel",
    "member"
  ],
  [
    "src/progress.js~progress#constructor",
    "class/src/progress.js~Progress.html#instance-constructor-constructor",
    "src/progress.js~Progress#constructor",
    "method"
  ],
  [
    "src/progress.js~progress#description",
    "class/src/progress.js~Progress.html#instance-member-description",
    "src/progress.js~Progress#description",
    "member"
  ],
  [
    "src/progress.js~progress#earliestfirsttime",
    "class/src/progress.js~Progress.html#instance-member-earliestFirstTime",
    "src/progress.js~Progress#earliestFirstTime",
    "member"
  ],
  [
    "src/progress.js~progress#earliestupdatetime",
    "class/src/progress.js~Progress.html#instance-member-earliestUpdateTime",
    "src/progress.js~Progress#earliestUpdateTime",
    "member"
  ],
  [
    "src/progress.js~progress#firstdelay",
    "class/src/progress.js~Progress.html#instance-member-firstDelay",
    "src/progress.js~Progress#firstDelay",
    "member"
  ],
  [
    "src/progress.js~progress#getprogressfraction",
    "class/src/progress.js~Progress.html#instance-method-getProgressFraction",
    "src/progress.js~Progress#getProgressFraction",
    "method"
  ],
  [
    "src/progress.js~progress#inprogress",
    "class/src/progress.js~Progress.html#instance-member-inProgress",
    "src/progress.js~Progress#inProgress",
    "member"
  ],
  [
    "src/progress.js~progress#initcomplete",
    "class/src/progress.js~Progress.html#instance-member-initComplete",
    "src/progress.js~Progress#initComplete",
    "member"
  ],
  [
    "src/progress.js~progress#isballottreeused",
    "class/src/progress.js~Progress.html#instance-member-isBallotTreeUsed",
    "src/progress.js~Progress#isBallotTreeUsed",
    "member"
  ],
  [
    "src/progress.js~progress#isdynamictreeused",
    "class/src/progress.js~Progress.html#instance-member-isDynamicTreeUsed",
    "src/progress.js~Progress#isDynamicTreeUsed",
    "member"
  ],
  [
    "src/progress.js~progress#istimetoupdate",
    "class/src/progress.js~Progress.html#instance-method-isTimeToUpdate",
    "src/progress.js~Progress#isTimeToUpdate",
    "method"
  ],
  [
    "src/progress.js~progress#maxnbriterations",
    "class/src/progress.js~Progress.html#instance-member-maxNbrIterations",
    "src/progress.js~Progress#maxNbrIterations",
    "member"
  ],
  [
    "src/progress.js~progress#nbrballotgroups",
    "class/src/progress.js~Progress.html#instance-member-nbrBallotGroups",
    "src/progress.js~Progress#nbrBallotGroups",
    "member"
  ],
  [
    "src/progress.js~progress#nbroriginalhopefuls",
    "class/src/progress.js~Progress.html#instance-member-nbrOriginalHopefuls",
    "src/progress.js~Progress#nbrOriginalHopefuls",
    "member"
  ],
  [
    "src/progress.js~progress#nbrresolvedhopefuls",
    "class/src/progress.js~Progress.html#instance-member-nbrResolvedHopefuls",
    "src/progress.js~Progress#nbrResolvedHopefuls",
    "member"
  ],
  [
    "src/progress.js~progress#otherbase",
    "class/src/progress.js~Progress.html#instance-member-otherBase",
    "src/progress.js~Progress#otherBase",
    "member"
  ],
  [
    "src/progress.js~progress#othercompleted",
    "class/src/progress.js~Progress.html#instance-member-otherCompleted",
    "src/progress.js~Progress#otherCompleted",
    "member"
  ],
  [
    "src/progress.js~progress#progress",
    "class/src/progress.js~Progress.html#instance-member-progress",
    "src/progress.js~Progress#progress",
    "member"
  ],
  [
    "src/progress.js~progress#setcallback",
    "class/src/progress.js~Progress.html#instance-method-setCallback",
    "src/progress.js~Progress#setCallback",
    "method"
  ],
  [
    "src/progress.js~progress#setdynamictreeinitprogress",
    "class/src/progress.js~Progress.html#instance-method-setDynamicTreeInitProgress",
    "src/progress.js~Progress#setDynamicTreeInitProgress",
    "method"
  ],
  [
    "src/progress.js~progress#setearliestupdatetime",
    "class/src/progress.js~Progress.html#instance-method-setEarliestUpdateTime",
    "src/progress.js~Progress#setEarliestUpdateTime",
    "method"
  ],
  [
    "src/progress.js~progress#setiterationprogress",
    "class/src/progress.js~Progress.html#instance-method-setIterationProgress",
    "src/progress.js~Progress#setIterationProgress",
    "method"
  ],
  [
    "src/progress.js~progress#setnbrballotgroups",
    "class/src/progress.js~Progress.html#instance-method-setNbrBallotGroups",
    "src/progress.js~Progress#setNbrBallotGroups",
    "method"
  ],
  [
    "src/progress.js~progress#setnbroriginalhopefuls",
    "class/src/progress.js~Progress.html#instance-method-setNbrOriginalHopefuls",
    "src/progress.js~Progress#setNbrOriginalHopefuls",
    "method"
  ],
  [
    "src/progress.js~progress#setroundprogress",
    "class/src/progress.js~Progress.html#instance-method-setRoundProgress",
    "src/progress.js~Progress#setRoundProgress",
    "method"
  ],
  [
    "src/progress.js~progress#settreebuildprogress",
    "class/src/progress.js~Progress.html#instance-method-setTreeBuildProgress",
    "src/progress.js~Progress#setTreeBuildProgress",
    "method"
  ],
  [
    "src/progress.js~progress#setvalidationprogress",
    "class/src/progress.js~Progress.html#instance-method-setValidationProgress",
    "src/progress.js~Progress#setValidationProgress",
    "method"
  ],
  [
    "src/progress.js~progress#starttime",
    "class/src/progress.js~Progress.html#instance-member-startTime",
    "src/progress.js~Progress#startTime",
    "member"
  ],
  [
    "src/progress.js~progress#starttimers",
    "class/src/progress.js~Progress.html#instance-method-startTimers",
    "src/progress.js~Progress#startTimers",
    "method"
  ],
  [
    "src/progress.js~progress#treebuildperiod",
    "class/src/progress.js~Progress.html#instance-member-treeBuildPeriod",
    "src/progress.js~Progress#treeBuildPeriod",
    "member"
  ],
  [
    "src/progress.js~progress#treeinitperiod",
    "class/src/progress.js~Progress.html#instance-member-treeInitPeriod",
    "src/progress.js~Progress#treeInitPeriod",
    "member"
  ],
  [
    "src/progress.js~progress#updatedelay",
    "class/src/progress.js~Progress.html#instance-member-updateDelay",
    "src/progress.js~Progress#updateDelay",
    "member"
  ],
  [
    "src/progress.js~progress#updatetimers",
    "class/src/progress.js~Progress.html#instance-method-updateTimers",
    "src/progress.js~Progress#updateTimers",
    "method"
  ],
  [
    "src/progress.js~progress#useballottree",
    "class/src/progress.js~Progress.html#instance-method-useBallotTree",
    "src/progress.js~Progress#useBallotTree",
    "method"
  ],
  [
    "src/progress.js~progress#validationcomplete",
    "class/src/progress.js~Progress.html#instance-member-validationComplete",
    "src/progress.js~Progress#validationComplete",
    "member"
  ],
  [
    "src/progress.js~progress#validationperiod",
    "class/src/progress.js~Progress.html#instance-member-validationPeriod",
    "src/progress.js~Progress#validationPeriod",
    "member"
  ],
  [
    "src/results.js",
    "file/src/results.js.html",
    "src/results.js",
    "file"
  ],
  [
    "src/results.js~results#constructor",
    "class/src/results.js~Results.html#instance-constructor-constructor",
    "src/results.js~Results#constructor",
    "method"
  ],
  [
    "src/results.js~results#elected",
    "class/src/results.js~Results.html#instance-member-elected",
    "src/results.js~Results#elected",
    "member"
  ],
  [
    "src/results.js~results#getelectedasstring",
    "class/src/results.js~Results.html#instance-method-getElectedAsString",
    "src/results.js~Results#getElectedAsString",
    "method"
  ],
  [
    "src/results.js~results#getstatusesasstring",
    "class/src/results.js~Results.html#instance-method-getStatusesAsString",
    "src/results.js~Results#getStatusesAsString",
    "method"
  ],
  [
    "src/results.js~results#gettallyasstring",
    "class/src/results.js~Results.html#instance-method-getTallyAsString",
    "src/results.js~Results#getTallyAsString",
    "method"
  ],
  [
    "src/results.js~results#statuses",
    "class/src/results.js~Results.html#instance-member-statuses",
    "src/results.js~Results#statuses",
    "member"
  ],
  [
    "src/results.js~results#tally",
    "class/src/results.js~Results.html#instance-member-tally",
    "src/results.js~Results#tally",
    "member"
  ],
  [
    "src/results.js~results.comparesortkeys",
    "class/src/results.js~Results.html#static-method-compareSortKeys",
    "src/results.js~Results.compareSortKeys",
    "method"
  ],
  [
    "src/results.js~results.getelectedasstring",
    "class/src/results.js~Results.html#static-method-getElectedAsString",
    "src/results.js~Results.getElectedAsString",
    "method"
  ],
  [
    "src/results.js~results.getsortkey",
    "class/src/results.js~Results.html#static-method-getSortKey",
    "src/results.js~Results.getSortKey",
    "method"
  ],
  [
    "src/results.js~results.getstatusesasstring",
    "class/src/results.js~Results.html#static-method-getStatusesAsString",
    "src/results.js~Results.getStatusesAsString",
    "method"
  ],
  [
    "src/results.js~results.gettallyasstring",
    "class/src/results.js~Results.html#static-method-getTallyAsString",
    "src/results.js~Results.getTallyAsString",
    "method"
  ],
  [
    "src/results.js~results.gettallyorderasarray",
    "class/src/results.js~Results.html#static-method-getTallyOrderAsArray",
    "src/results.js~Results.getTallyOrderAsArray",
    "method"
  ],
  [
    "src/results.js~results.gettallyorderaslookup",
    "class/src/results.js~Results.html#static-method-getTallyOrderAsLookup",
    "src/results.js~Results.getTallyOrderAsLookup",
    "method"
  ],
  [
    "src/status.js",
    "file/src/status.js.html",
    "src/status.js",
    "file"
  ],
  [
    "src/status.js~status#asarray",
    "class/src/status.js~Status.html#instance-method-asArray",
    "src/status.js~Status#asArray",
    "method"
  ],
  [
    "src/status.js~status#assimpleobject",
    "class/src/status.js~Status.html#instance-method-asSimpleObject",
    "src/status.js~Status#asSimpleObject",
    "method"
  ],
  [
    "src/status.js~status#candidate",
    "class/src/status.js~Status.html#instance-member-candidate",
    "src/status.js~Status#candidate",
    "member"
  ],
  [
    "src/status.js~status#constructor",
    "class/src/status.js~Status.html#instance-constructor-constructor",
    "src/status.js~Status#constructor",
    "method"
  ],
  [
    "src/status.js~status#destiny",
    "class/src/status.js~Status.html#instance-member-destiny",
    "src/status.js~Status#destiny",
    "member"
  ],
  [
    "src/status.js~status#isequal",
    "class/src/status.js~Status.html#instance-method-isEqual",
    "src/status.js~Status#isEqual",
    "method"
  ],
  [
    "src/status.js~status#isnotequal",
    "class/src/status.js~Status.html#instance-method-isNotEqual",
    "src/status.js~Status#isNotEqual",
    "method"
  ],
  [
    "src/status.js~status#keepfactor",
    "class/src/status.js~Status.html#instance-member-keepFactor",
    "src/status.js~Status#keepFactor",
    "member"
  ],
  [
    "src/status.js~status#nbrround",
    "class/src/status.js~Status.html#instance-member-nbrRound",
    "src/status.js~Status#nbrRound",
    "member"
  ],
  [
    "src/status.js~status#status",
    "class/src/status.js~Status.html#instance-member-status",
    "src/status.js~Status#status",
    "member"
  ],
  [
    "src/status.js~status#tostring",
    "class/src/status.js~Status.html#instance-method-toString",
    "src/status.js~Status#toString",
    "method"
  ],
  [
    "src/status.js~status#votes",
    "class/src/status.js~Status.html#instance-member-votes",
    "src/status.js~Status#votes",
    "member"
  ],
  [
    "src/util_basic.js",
    "file/src/util_basic.js.html",
    "src/util_basic.js",
    "file"
  ],
  [
    "src/util_basic.js~utilbaseerror#constructor",
    "class/src/util_basic.js~UtilBaseError.html#instance-constructor-constructor",
    "src/util_basic.js~UtilBaseError#constructor",
    "method"
  ],
  [
    "src/util_basic.js~utilbaseerror#message",
    "class/src/util_basic.js~UtilBaseError.html#instance-member-message",
    "src/util_basic.js~UtilBaseError#message",
    "member"
  ],
  [
    "src/util_basic.js~utilbaseerror#name",
    "class/src/util_basic.js~UtilBaseError.html#instance-member-name",
    "src/util_basic.js~UtilBaseError#name",
    "member"
  ],
  [
    "src/util_basic.js~utilbaseerror#othervalues",
    "class/src/util_basic.js~UtilBaseError.html#instance-member-otherValues",
    "src/util_basic.js~UtilBaseError#otherValues",
    "member"
  ],
  [
    "src/util_basic.js~utilbaseerror#priorerror",
    "class/src/util_basic.js~UtilBaseError.html#instance-member-priorError",
    "src/util_basic.js~UtilBaseError#priorError",
    "member"
  ],
  [
    "src/util_basic.js~utilbaseerror#priorerrordescription",
    "class/src/util_basic.js~UtilBaseError.html#instance-member-priorErrorDescription",
    "src/util_basic.js~UtilBaseError#priorErrorDescription",
    "member"
  ],
  [
    "src/util_basic.js~utilbaseerror#tostring",
    "class/src/util_basic.js~UtilBaseError.html#instance-method-toString",
    "src/util_basic.js~UtilBaseError#toString",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.describeerror",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-describeError",
    "src/util_basic.js~UtilBasicFunctions.describeError",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getclassnameof",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getClassNameOf",
    "src/util_basic.js~UtilBasicFunctions.getClassNameOf",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getitems",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getItems",
    "src/util_basic.js~UtilBasicFunctions.getItems",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getkeys",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getKeys",
    "src/util_basic.js~UtilBasicFunctions.getKeys",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getnames",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getNames",
    "src/util_basic.js~UtilBasicFunctions.getNames",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getownitems",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getOwnItems",
    "src/util_basic.js~UtilBasicFunctions.getOwnItems",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getownnames",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getOwnNames",
    "src/util_basic.js~UtilBasicFunctions.getOwnNames",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getownvalues",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getOwnValues",
    "src/util_basic.js~UtilBasicFunctions.getOwnValues",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getsortedkeys",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getSortedKeys",
    "src/util_basic.js~UtilBasicFunctions.getSortedKeys",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.getvalues",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-getValues",
    "src/util_basic.js~UtilBasicFunctions.getValues",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.indentmessage",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-indentMessage",
    "src/util_basic.js~UtilBasicFunctions.indentMessage",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.setdifference",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-setDifference",
    "src/util_basic.js~UtilBasicFunctions.setDifference",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.setintersection",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-setIntersection",
    "src/util_basic.js~UtilBasicFunctions.setIntersection",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.setunion",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-setUnion",
    "src/util_basic.js~UtilBasicFunctions.setUnion",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.show",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-show",
    "src/util_basic.js~UtilBasicFunctions.show",
    "method"
  ],
  [
    "src/util_basic.js~utilbasicfunctions.toarrayofstrings",
    "class/src/util_basic.js~UtilBasicFunctions.html#static-method-toArrayOfStrings",
    "src/util_basic.js~UtilBasicFunctions.toArrayOfStrings",
    "method"
  ],
  [
    "src/util_basic.js~utilvalueerror#constructor",
    "class/src/util_basic.js~UtilValueError.html#instance-constructor-constructor",
    "src/util_basic.js~UtilValueError#constructor",
    "method"
  ],
  [
    "src/validate.js",
    "file/src/validate.js.html",
    "src/validate.js",
    "file"
  ],
  [
    "src/validate.js~validator#ballots",
    "class/src/validate.js~Validator.html#instance-method-ballots",
    "src/validate.js~Validator#ballots",
    "method"
  ],
  [
    "src/validate.js~validator#candidates",
    "class/src/validate.js~Validator.html#instance-method-candidates",
    "src/validate.js~Validator#candidates",
    "method"
  ],
  [
    "src/validate.js~validator#excluded",
    "class/src/validate.js~Validator.html#instance-method-excluded",
    "src/validate.js~Validator#excluded",
    "method"
  ],
  [
    "src/validate.js~validator#maxrankinglevels",
    "class/src/validate.js~Validator.html#instance-method-maxRankingLevels",
    "src/validate.js~Validator#maxRankingLevels",
    "method"
  ],
  [
    "src/validate.js~validator#nbrseatstofill",
    "class/src/validate.js~Validator.html#instance-method-nbrSeatsToFill",
    "src/validate.js~Validator#nbrSeatsToFill",
    "method"
  ],
  [
    "src/validate.js~validator#options",
    "class/src/validate.js~Validator.html#instance-method-options",
    "src/validate.js~Validator#options",
    "method"
  ],
  [
    "src/validate.js~validator#protectedcandidates",
    "class/src/validate.js~Validator.html#instance-method-protectedCandidates",
    "src/validate.js~Validator#protectedCandidates",
    "method"
  ],
  [
    "src/validate.js~validator#tiebreaker",
    "class/src/validate.js~Validator.html#instance-method-tieBreaker",
    "src/validate.js~Validator#tieBreaker",
    "method"
  ],
  [
    "src/validate.js~validator.issafeinteger",
    "class/src/validate.js~Validator.html#static-method-isSafeInteger",
    "src/validate.js~Validator.isSafeInteger",
    "method"
  ],
  [
    "src/validate.js~validator.toarrayofstrings",
    "class/src/validate.js~Validator.html#static-method-toArrayOfStrings",
    "src/validate.js~Validator.toArrayOfStrings",
    "method"
  ],
  [
    "src/with_json.js",
    "file/src/with_json.js.html",
    "src/with_json.js",
    "file"
  ],
  [
    "src/with_json.js~withjson.buildtabulateargs",
    "class/src/with_json.js~WithJson.html#static-method-buildTabulateArgs",
    "src/with_json.js~WithJson.buildTabulateArgs",
    "method"
  ],
  [
    "src/with_json.js~withjson.clitabulate",
    "class/src/with_json.js~WithJson.html#static-method-cliTabulate",
    "src/with_json.js~WithJson.cliTabulate",
    "method"
  ],
  [
    "src/with_json.js~withjson.readfile",
    "class/src/with_json.js~WithJson.html#static-method-readFile",
    "src/with_json.js~WithJson.readFile",
    "method"
  ],
  [
    "src/with_json.js~withjson.readjson",
    "class/src/with_json.js~WithJson.html#static-method-readJson",
    "src/with_json.js~WithJson.readJson",
    "method"
  ],
  [
    "src/with_json.js~withjson.readoptionaljson",
    "class/src/with_json.js~WithJson.html#static-method-readOptionalJson",
    "src/with_json.js~WithJson.readOptionalJson",
    "method"
  ],
  [
    "src/with_json.js~withjson.readtabulationspec",
    "class/src/with_json.js~WithJson.html#static-method-readTabulationSpec",
    "src/with_json.js~WithJson.readTabulationSpec",
    "method"
  ],
  [
    "src/with_json.js~withjson.resultstojsonstring",
    "class/src/with_json.js~WithJson.html#static-method-resultsToJsonString",
    "src/with_json.js~WithJson.resultsToJsonString",
    "method"
  ],
  [
    "src/with_json.js~withjson.tabulate",
    "class/src/with_json.js~WithJson.html#static-method-tabulate",
    "src/with_json.js~WithJson.tabulate",
    "method"
  ],
  [
    "src/with_json.js~withjson.writefile",
    "class/src/with_json.js~WithJson.html#static-method-writeFile",
    "src/with_json.js~WithJson.writeFile",
    "method"
  ]
]